_BASE_: Base-Cityscapes-SemanticSegmentation.yaml
MODEL:
  META_ARCHITECTURE: "MaskFormer"
  SEM_SEG_HEAD:
    NAME: "MaskFormerHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 19
    LOSS_WEIGHT: 1.0
    CONVS_DIM: 256
    MASK_DIM: 256
    NORM: "GN"
    # pixel decoder
    PIXEL_DECODER_NAME: "MSDeformAttnPixelDecoder"
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    DEFORMABLE_TRANSFORMER_ENCODER_IN_FEATURES: ["res3", "res4", "res5"]
    COMMON_STRIDE: 4
    TRANSFORMER_ENC_LAYERS: 6
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "SuperPixelQueryTransformerDecoder"
    TRANSFORMER_IN_FEATURE: "multi_scale_pixel_decoder"
    HIDDEN_DIM: 256
    NUM_OBJECT_QUERIES: 100
    NHEADS: 8
    DROPOUT: 0.0
    DIM_FEEDFORWARD: 2048
    ENC_LAYERS: 0
    DEC_LAYERS: 10
    PRE_NORM: False
    DEEP_SUPERVISION: True
    NO_OBJECT_WEIGHT: 0.1
    ENFORCE_INPUT_PROJ: False
    # SuperPixel-specific configs
    ENABLE_SUPERPIXEL: True
    SUPERPIXEL_FUSION_DIM: 128
    SUPERPIXEL_FEATURE_TYPE: "id_embedding"  # or "spatial"
    FUSION_STRATEGY: "concat_mlp"  # or "add", "attention"
    # SuperPixel generation parameters
    SUPERPIXEL_ALGORITHM: "slic"
    SUPERPIXEL_N_SEGMENTS: 100
    SUPERPIXEL_COMPACTNESS: 10
    SUPERPIXEL_SIGMA: 1
  RESNETS:
    NORM: "BN"  # 改为BN，而不是SyncBN
DATASETS:
  TRAIN: ("cityscapes_fine_sem_seg_train",)
  TEST: ("cityscapes_fine_sem_seg_val",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.0001
  STEPS: (65000, 80000)
  MAX_ITER: 90000
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
VERSION: 2
